# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170817_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframe',
            options={'verbose_name_plural': 'IFrames'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='iframe',
            field=models.ManyToManyField(blank=True, null=True, related_name='iframe', to='organization.IFrame'),
        ),
    ]
