# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170817_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
