# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170817_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframe',
            options={'verbose_name': 'IFrame', 'verbose_name_plural': 'IFrames'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='iframe',
        ),
    ]
