# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170818_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iframe_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iframe',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iframe_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
