# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('family_number', models.CharField(blank=True, max_length=1000)),
                ('temporary_location', models.CharField(blank=True, default='', max_length=1000)),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warning.Thana')),
            ],
        ),
        migrations.CreateModel(
            name='WarningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.IntegerField(choices=[(0, 'Storm'), (1, 'Earthquake')])),
                ('value', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WarningSmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warning.Thana')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warning.WarningModel')),
            ],
        ),
        migrations.AddField(
            model_name='temporarylocation',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warning.Thana'),
        ),
        migrations.AddField(
            model_name='lostmodel',
            name='family',
            field=models.ManyToManyField(blank=True, related_name='family', to='warning.User'),
        ),
        migrations.AddField(
            model_name='lostmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='warning.User'),
        ),
    ]
