# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
