# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageChangesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PagePayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageSubscribersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageValueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('page_changes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_bot.PageChangesModel')),
            ],
        ),
        migrations.AddField(
            model_name='pageentrymodel',
            name='payload_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_bot.PagePayloadModel'),
        ),
        migrations.AddField(
            model_name='pagechangesmodel',
            name='page_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_bot.PageEntryModel'),
        ),
    ]
