# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_bot', '0003_auto_20171201_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesubscribersmodel',
            name='subscriber_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
