# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(max_length=1000)),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FacebookIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.IntegerField()),
                ('user_type', models.IntegerField(choices=[(1, 'Sender'), (2, 'Recipient')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=500)),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessagingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.EntryModel')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.MessageDetailModel')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='bot.FacebookIdModel')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bot.FacebookIdModel')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerPayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('sticker_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='messenger_payload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.MessengerPayloadModel'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.MessageDetailModel'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='payload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.PayloadModel'),
        ),
    ]
