# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(max_length=1000)),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('sticker_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='messagedetailmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='facebookidmodel',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Sender'), (2, 'Recipient')], null=True),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.MessageDetailModel'),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='payload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.PayloadModel'),
        ),
    ]
