# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessagingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaging_type', models.CharField(choices=[('RESPONSE', 'Response'), ('UPDATE', 'Update'), ('MESSAGE_TAG', 'Message Tag'), ('NON_PROMOTIONAL_SUBSCRIPTION', 'Non Promotional Subscription')], max_length=1000, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.AttachmentModel')),
            ],
        ),
        migrations.DeleteModel(
            name='DummyModel',
        ),
        migrations.AddField(
            model_name='payloadmodel',
            name='is_reusable',
            field=models.NullBooleanField(help_text='Only applicable when sending messages as a response'),
        ),
        migrations.AlterField(
            model_name='facebookidmodel',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Sender'), (2, 'Recipient')], null=True),
        ),
        migrations.AddField(
            model_name='sendmessagingmodel',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.FacebookIdModel'),
        ),
    ]
