# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookidmodel',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Sender'), (2, 'Recipient')], null=True),
        ),
    ]
