# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171023_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
