# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_payloadmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
